### ISSUE TITLE
"Missing UnrealGame binary" error

### ISSUE THREAD

**Issue by JunyDeveloper** [localcc/PalworldModdingKit#17]
Hello. I got this error when packaging my project and wondering if ya'll know what's going on.

```
Missing UnrealGame binary.
You may have to build the UE project with your IDE. Alternatively, build using UnrealBuildTool with the commandline:
UnrealGame <Platform> <Configuration>
```

One thing I notice was this in the logs:
`[2024.01.27-06.52.24:907][ 76]UATHelper: Packaging (Windows): ERROR: Stage Failed. Missing receipt 'C:\Users\*****\Downloads\PalworldModdingKit-main\PalworldModdingKit-main\Binaries\Win64\PalGame.target'. Check that this target has been built.`

[Pal.log](https://github.com/localcc/PalworldModdingKit/files/14071383/Pal.log)

**Comment by localcc** [comment]
Try right clicking the uproject, generate visual studio
Files, open the generated sln in vs2022 and compile in DevelopmentEditor configuration

**Comment by JunyDeveloper** [comment]
Thank you that worked!
