### ISSUE TITLE
Unable to successfully initialize 'Pal' // Pal could not be compiled, try rebuilding from source manually

### ISSUE THREAD

**Issue by ryman230** [localcc/PalworldModdingKit#2]
I'm running into these two error codes, followed by an crash log, which I'll attach in addition to the screenshots of the whole dealio.
[Pal_4.log](https://github.com/localcc/PalworldModdingKit/files/14032296/Pal_4.log)
![Screenshot (112)](https://github.com/localcc/PalworldModdingKit/assets/36091717/1c367314-f42e-4892-9d65-99322f8745ce)

I heard through the "Palworld Modding Community" Discord server that it was probably due to an incorrect or missing Wwise installation, so I went through and restarted from scratch only to have the same issue. What do you guys make of it?

**Comment by ryman230** [comment]
So a quick follow-up before I sign off for the night, I received a working build from a fellow discord user on the modding community. Which shows that I did in-fact trip up in your instructions somewhere. I'll look into what I did wrong and post it here tomorrow to make sure anyone with similar issues doesn't trip up. Though if you happen to reply localcc, you may have a better idea of what I did wrong!

**Comment by localcc** [comment]
Fixed by #1

**Comment by YaibaToKen** [comment]
> So a quick follow-up before I sign off for the night, I received a working build from a fellow discord user on the modding community. Which shows that I did in-fact trip up in your instructions somewhere. I'll look into what I did wrong and post it here tomorrow to make sure anyone with similar issues doesn't trip up. Though if you happen to reply localcc, you may have a better idea of what I did wrong!

Any news on this? Facing the same issue and even after retracing my steps though the README can't figure out what's wrong.

**Comment by tetsune** [comment]
I, too, am facing this issue... I would like to know what I am doing wrong lol
