### ISSUE TITLE
EAV caused by Wwise

### ISSUE THREAD

**Issue by Nixdorfer** [localcc/PalworldModdingKit#20]
Every time I try to start the mod preview, which is when I click the green play button, the game immediately crashes and displays the following message:
```
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x000000000000035d
UnrealEditor_AkAudio!FAkAudioDevice::RemoveDefaultListener() [...\Plugins\Wwise\Source\AkAudio\Private\AkAudioDevice.cpp:3956]
UnrealEditor_AkAudio!TBaseRawMethodDelegateInstance<0,FAkAudioDevice,void __cdecl(bool),FDefaultDelegateUserPolicy>::ExecuteIfSafe() [C:\Program Files\Epic Games\UE_5.1\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:476]
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll
```
I've tried adding to `.../Config/Windows/WindowsEngine.ini` and writing:
```
[Audio]
AudioDeviceModuleName=
AudioMixerModuleName=
```
to fix this issue, but it didn't work. Restarting the computer also didn't help.
Then, I tried a somewhat "burying my head in the sand" approach by commenting out the faulty line in the file, specifically the statement in `...\Plugins\Wwise\Source\AkAudio\Private\AkAudioDevice.cpp`:
`in_pListener->IsDefaultListener = true;`
It sounds foolish, but I thought it might shift the problem elsewhere to provide more information. However, the error still stubbornly occurs at the same spot.
Additionally, an error stating 'File not Found' occurred in the Project Settings > Wwise > Integration Settings > Wwise Project Path, because it points to a file `Testing.wproj` located in `../../Documents/WwiseProjects/Testing`. I'm unsure if this is causing the issue, as I have never used Wwise before.

**Comment by Wastarch** [comment]
牛逼啊，大哥   Awesome,bro

**Comment by Wastarch** [comment]
I am also AkAudioDevice.cpp:3956, but I still reported an error after adding nullptr checks

**Comment by Wastarch** [comment]
same error

**Comment by Wastarch** [comment]
after changed the code,it still have error AkAudioDevice.cpp:3959

**Comment by yuejiewudi1997** [comment]
谢谢，非常有效！

**Comment by Noveleth** [comment]
感谢大佬，这个问题卡了我两个小时，终于在你这边解决了，非常感谢！
