### ISSUE TITLE
Module.Pal.91_of_94.cpp.obj: Error LNK2019 : unresolved external symbol "__declspec(dllimport) public: __cdecl UAkComponent::UAkComponent(void)" (__imp_??0UAkComponent@@QEAA@XZ) referenced in function "public: __cdecl UPalAkComponent::UPalAkComponent(void)" (??0UPalAkComponent@@QEAA@XZ)

### ISSUE THREAD

**Issue by jakcqc** [localcc/PalworldModdingKit#24]
Built using visual studio 2022, Wwise 5.1 has been automatically integrated with project, with correct files. I am using jetbrains rider, but it is using correct VStudio build (2022). Does this mean I need to do an offline Wwise sdk integration or?

**Comment by localcc** [comment]
I think the guide mentions doing the offline integration way for wwise, try that

**Comment by jakcqc** [comment]
When I downloading Wwise, it seemed to only give me the offline files for 5.1,5.2,5.3. Do you have a link to the Wwise 5.0 files? I am also confused since the Pal.uproject is a 5.1.1 project...

**Comment by jakcqc** [comment]
> try [#19 (comment)](https://github.com/localcc/PalworldModdingKit/issues/19#issuecomment-1920505020)

Trying this later today, thank you!

**Comment by jakcqc** [comment]
> try [#19 (comment)](https://github.com/localcc/PalworldModdingKit/issues/19#issuecomment-1920505020)

This worked! I launched project no issues. Thank you super much.
