### ISSUE TITLE
Missing MapBase file

### ISSUE THREAD

**Issue by miapuffia** [localcc/PalworldModdingKit#25]
Doing a header dump from UE4SS creates a few files that aren't available in the modding kit. One of those is WBP_Map_Base with the class UWBP_Map_Base_C. I'm trying to use this class to add icons to the map. Is there a reason it's missing?

**Comment by localcc** [comment]
CXX header dump contains blueprint classes which will be uncooked and included at some point, for now just create an asset with same type and inheritance at the same path in the editor, and create the required variable there, make sure to assign the asset to chunk 0 so it doesn't get packaged with your mod. This is basically dummying an asset so your mod can reference it.

**Comment by miapuffia** [comment]
Can you point me to any examples of doing this? "same path in the editor, and create the required variable there" is the part I don't fully understand.
